### ISSUE TITLE
Please supplement user manual

### ISSUE THREAD

**Issue by evaniswong** [Weifanwong/zhihu_spider#1]
你好 ，可以简单介绍一下怎么用吗 ？

**Comment by Weifanwong** [comment]
抱歉 现在才看到你的回复

请您将该文件下载至任意目录，在cmd终端窗口中进入.../zhihu/zhihu/目录，输入
scrapy crawl zhihu_login 即可爬取根用户信息以及他的粉丝、关注列表。
